# Generated by Django 4.2.7 on 2023-12-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_loggingmoves_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingmoves',
            name='ip_address',
            field=models.CharField(max_length=255),
        ),
    ]
